// chiamate per prendere tutte le starships
export const FETCH_ALL_STARSHIPS_REQUEST = 'FETCH_ALL_STARSHIPS_REQUEST'
export const FETCH_ALL_STARSHIPS_SUCCESS = 'FETCH_ALL_STARSHIPS_SUCCESS'
export const FETCH_ALL_STARSHIPS_ERROR = 'FETCH_ALL_STARSHIPS_ERROR'

// chiamate per cancellare una starship
export const DELETE_STARSHIP_REQUEST = 'DELETE_STARSHIP_REQUEST'
export const DELETE_STARSHIP_SUCCESS = 'DELETE_STARSHIP_SUCCESS'
export const DELETE_STARSHIP_ERROR = 'DELETE_STARSHIP_ERROR'

//chiamate per aggiungere una starship
export const ADD_STARSHIP_REQUEST = 'ADD_STARSHIP_REQUEST'
export const ADD_STARSHIP_ERROR = 'ADD_STARSHIP_ERROR'
export const ADD_STARSHIP_SUCCESS = 'ADD_STARSHIP_SUCCESS'

// per rimuovere errore
export const DISCARD_ERROR = 'DISCARD_ERROR'
