// chiamate per prendere tutte le starships
export const FETCH_ALL_STARSHIPS_REQUEST = 'FETCH_ALL_STARSHIPS_REQUEST'
export const FETCH_ALL_STARSHIPS_SUCCESS = 'FETCH_ALL_STARSHIPS_SUCCESS'
export const FETCH_ALL_STARSHIPS_ERROR = 'FETCH_ALL_STARSHIPS_ERROR'

// chiamate per cancellare una starships
export const DELETE_ALL_STARSHIPS_REQUEST = 'DELETE_ALL_STARSHIPS_REQUEST'
export const DELETE_ALL_STARSHIPS_SUCCESS = 'DELETE_ALL_STARSHIPS_SUCCESS'
export const DELETE_ALL_STARSHIPS_ERROR = 'DELETE_ALL_STARSHIPS_ERROR'

// chiamate per aggiungere una starships
export const ADD_STARSHIPS_REQUEST = 'ADD_STARSHIPS_REQUEST'
export const ADD_STARSHIPS_SUCCESS = 'ADD_STARSHIPS_SUCCESS'
export const ADD_STARSHIPS_ERROR = 'ADD_STARSHIPS_ERROR'

// per rimuovere l'error
export const DISCARD_ERROR = 'DISCARD_ERROR'